# Generated by Django 5.0.1 on 2024-01-16 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_goodmodel_imagemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodmodel',
            options={'verbose_name': 'Good', 'verbose_name_plural': 'Goods'},
        ),
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='goodmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 16, 18, 10, 42, 179434, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='GoodVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goods', models.ManyToManyField(to='catalog.goodmodel')),
            ],
            options={
                'verbose_name': 'Variation',
                'verbose_name_plural': 'Variations',
            },
        ),
    ]
