# Generated by Django 5.0.1 on 2024-01-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_goodmodel_options_alter_imagemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodvariations',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
